name: Inaccurate directions/content
description: Report inaccurate directions or information.
title: "inaccuracy: "
labels: [inaccuracy]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the website! Please fill out the form below.
  - type: dropdown
    attributes:
      label: Which sheet does this relate to?
      options:
        - Walkthrough
        - DLC Walkthrough
        - NPC Walkthrough
        - Questlines
        - Bosses
        - Merchants
        - Achievements
        - Weapons
        - Armor
        - Ashes
        - Spells
        - Talismans
        - Key Items
        - Miscellaneous Items
        - New Game Plus
        - Resources
      multiple: true
    validations:
      required: true
  - type: input
    attributes:
      label: Which section contains the inaccurate text?
      description: Name one or multiple sections.
      placeholder: E.g. Limgrave, Stormveil Castle...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current inaccurate text
      description: Paste the sentence or paragraph that is inaccurate.
      placeholder: Paste the inaccurate text...
    validations:
      required: true
  - type: textarea
    attributes:
      label: What's inaccurate?
      description: Describe what part of the text is inaccurate.
      placeholder: Describe what's inaccurate...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggest a correction
      description: Suggest your corrected version.
      placeholder: Suggest your corrected text...
