name: Unclear descriptions
description: Report unclear, confusing or hard-to-follow descriptions.
title: "clarify: "
labels: [clarify]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the website! Please fill out the form below.

        You can also use this template to report typos or grammatical errors.
  - type: dropdown
    attributes:
      label: Which sheet does this relate to?
      options:
        - Walkthrough
        - DLC Walkthrough
        - NPC Walkthrough
        - Questlines
        - Bosses
        - Merchants
        - Achievements
        - Weapons
        - Armor
        - Ashes
        - Spells
        - Talismans
        - Key Items
        - Miscellaneous Items
        - New Game Plus
        - Resources
      multiple: true
    validations:
      required: true
  - type: input
    attributes:
      label: Which section contains the unclear text?
      description: Name one or multiple sections.
      placeholder: E.g. Limgrave, Stormveil Castle...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current unclear text
      description: Paste the sentence or paragraph that is unclear or confusing.
      placeholder: Paste the unclear text...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggest a rewrite
      description: Suggest a rewrite, or explain what could be improved.
      placeholder: Suggest a clearer version, or explain what's unclear...
